//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for AlertType.
const (
	AlertTypeAlert   AlertType = "alert"
	AlertTypeInfo    AlertType = "info"
	AlertTypeSuccess AlertType = "success"
)

// Defines values for FullSpeechSentiment.
const (
	FullSpeechSentimentNegativ      FullSpeechSentiment = "negativ"
	FullSpeechSentimentNeutral      FullSpeechSentiment = "neutral"
	FullSpeechSentimentPositiv      FullSpeechSentiment = "positiv"
	FullSpeechSentimentStarkNegativ FullSpeechSentiment = "stark negativ"
	FullSpeechSentimentStarkPositiv FullSpeechSentiment = "stark positiv"
)

// Defines values for SpeechDetailSentiment.
const (
	SpeechDetailSentimentNegativ      SpeechDetailSentiment = "negativ"
	SpeechDetailSentimentNeutral      SpeechDetailSentiment = "neutral"
	SpeechDetailSentimentPositiv      SpeechDetailSentiment = "positiv"
	SpeechDetailSentimentStarkNegativ SpeechDetailSentiment = "stark negativ"
	SpeechDetailSentimentStarkPositiv SpeechDetailSentiment = "stark positiv"
)

// Defines values for SpeechSnippetSentiment.
const (
	Negativ      SpeechSnippetSentiment = "negativ"
	Neutral      SpeechSnippetSentiment = "neutral"
	Positiv      SpeechSnippetSentiment = "positiv"
	StarkNegativ SpeechSnippetSentiment = "stark negativ"
	StarkPositiv SpeechSnippetSentiment = "stark positiv"
)

// Defines values for TopicTrend.
const (
	TopicTrendDown   TopicTrend = "down"
	TopicTrendStable TopicTrend = "stable"
	TopicTrendUp     TopicTrend = "up"
)

// Defines values for TopicDetailTrend.
const (
	TopicDetailTrendDown   TopicDetailTrend = "down"
	TopicDetailTrendStable TopicDetailTrend = "stable"
	TopicDetailTrendUp     TopicDetailTrend = "up"
)

// Alert defines model for Alert.
type Alert struct {
	Category  *string              `json:"category,omitempty"`
	Details   *NotificationDetails `json:"details,omitempty"`
	Id        *string              `json:"id,omitempty"`
	Message   *string              `json:"message,omitempty"`
	Timestamp *time.Time           `json:"timestamp,omitempty"`
	Title     *string              `json:"title,omitempty"`
	Type      *AlertType           `json:"type,omitempty"`
}

// AlertType defines model for Alert.Type.
type AlertType string

// Campaign defines model for Campaign.
type Campaign struct {
	Goal       *string    `json:"goal,omitempty"`
	Id         *string    `json:"id,omitempty"`
	LastUpdate *time.Time `json:"lastUpdate,omitempty"`
	Name       *string    `json:"name,omitempty"`
	Progress   *int       `json:"progress,omitempty"`
	Status     *string    `json:"status,omitempty"`
	TopicId    *string    `json:"topicId,omitempty"`
}

// CampaignInput defines model for CampaignInput.
type CampaignInput struct {
	Goal    *string `json:"goal,omitempty"`
	Name    *string `json:"name,omitempty"`
	TopicId *string `json:"topicId,omitempty"`
}

// DashboardData defines model for DashboardData.
type DashboardData struct {
	Alerts    *[]Alert          `json:"alerts,omitempty"`
	Stats     *[]DashboardStats `json:"stats,omitempty"`
	TrendData *[]TrendDataPoint `json:"trendData,omitempty"`
}

// DashboardStats defines model for DashboardStats.
type DashboardStats struct {
	Change     *string `json:"change,omitempty"`
	ChangeType *string `json:"changeType,omitempty"`
	Name       *string `json:"name,omitempty"`
	Value      *string `json:"value,omitempty"`
}

// FullSpeech defines model for FullSpeech.
type FullSpeech struct {
	Content       *string              `json:"content,omitempty"`
	Date          *time.Time           `json:"date,omitempty"`
	Duration      *string              `json:"duration,omitempty"`
	Id            *string              `json:"id,omitempty"`
	RelatedTopics *[]string            `json:"relatedTopics,omitempty"`
	Sentiment     *FullSpeechSentiment `json:"sentiment,omitempty"`
	Session       *string              `json:"session,omitempty"`
	SourceUrl     *string              `json:"sourceUrl,omitempty"`
	SpeakerId     *string              `json:"speakerId,omitempty"`
	Title         *string              `json:"title,omitempty"`
	TopicId       *string              `json:"topicId,omitempty"`
	Type          *string              `json:"type,omitempty"`
}

// FullSpeechSentiment defines model for FullSpeech.Sentiment.
type FullSpeechSentiment string

// Legislation defines model for Legislation.
type Legislation struct {
	Date    *time.Time `json:"date,omitempty"`
	Id      *string    `json:"id,omitempty"`
	Status  *string    `json:"status,omitempty"`
	Title   *string    `json:"title,omitempty"`
	TopicId *string    `json:"topicId,omitempty"`
}

// NotificationDetails defines model for NotificationDetails.
type NotificationDetails struct {
	After    *string `json:"after,omitempty"`
	Before   *string `json:"before,omitempty"`
	Reason   *string `json:"reason,omitempty"`
	Source   *string `json:"source,omitempty"`
	SpeechId *string `json:"speechId,omitempty"`
}

// PartyPosition defines model for PartyPosition.
type PartyPosition struct {
	Party     *string  `json:"party,omitempty"`
	Relevance *float32 `json:"relevance,omitempty"`
	Sentiment *float32 `json:"sentiment,omitempty"`
}

// Politician defines model for Politician.
type Politician struct {
	Age                *int        `json:"age,omitempty"`
	ContributionFactor *float32    `json:"contributionFactor,omitempty"`
	Gender             *string     `json:"gender,omitempty"`
	Id                 *string     `json:"id,omitempty"`
	Image              *string     `json:"image,omitempty"`
	Name               *string     `json:"name,omitempty"`
	Party              *string     `json:"party,omitempty"`
	Region             *string     `json:"region,omitempty"`
	Role               *string     `json:"role,omitempty"`
	Similar            *[]string   `json:"similar,omitempty"`
	TopTopics          *[]TopTopic `json:"topTopics,omitempty"`
	Volatility         *string     `json:"volatility,omitempty"`
}

// PoliticianDetail defines model for PoliticianDetail.
type PoliticianDetail struct {
	ActivityData       *[]TrendDataPoint `json:"activityData,omitempty"`
	Age                *int              `json:"age,omitempty"`
	ContributionFactor *float32          `json:"contributionFactor,omitempty"`
	Gender             *string           `json:"gender,omitempty"`
	Id                 *string           `json:"id,omitempty"`
	Image              *string           `json:"image,omitempty"`
	Name               *string           `json:"name,omitempty"`
	Party              *string           `json:"party,omitempty"`
	Region             *string           `json:"region,omitempty"`
	Role               *string           `json:"role,omitempty"`
	Similar            *[]string         `json:"similar,omitempty"`
	Speeches           *[]FullSpeech     `json:"speeches,omitempty"`
	TopTopics          *[]TopTopic       `json:"topTopics,omitempty"`
	Volatility         *string           `json:"volatility,omitempty"`
}

// Report defines model for Report.
type Report struct {
	Date *time.Time `json:"date,omitempty"`
	Id   *int       `json:"id,omitempty"`
	Name *string    `json:"name,omitempty"`
	Size *string    `json:"size,omitempty"`
}

// SearchResults defines model for SearchResults.
type SearchResults struct {
	Campaigns   *[]Campaign   `json:"campaigns,omitempty"`
	Politicians *[]Politician `json:"politicians,omitempty"`
	Topics      *[]Topic      `json:"topics,omitempty"`
}

// SessionStatus defines model for SessionStatus.
type SessionStatus struct {
	Datum          *time.Time `json:"datum,omitempty"`
	Error          *bool      `json:"error,omitempty"`
	Label          *string    `json:"label,omitempty"`
	Live           *bool      `json:"live,omitempty"`
	NextDatum      *time.Time `json:"nextDatum"`
	Sitzungsnummer *string    `json:"sitzungsnummer,omitempty"`
	Titel          *string    `json:"titel,omitempty"`
	Wahlperiode    *int       `json:"wahlperiode,omitempty"`
}

// SpeechDetail defines model for SpeechDetail.
type SpeechDetail struct {
	Content       *string                `json:"content,omitempty"`
	Date          *time.Time             `json:"date,omitempty"`
	Duration      *string                `json:"duration,omitempty"`
	Id            *string                `json:"id,omitempty"`
	RelatedTopics *[]string              `json:"relatedTopics,omitempty"`
	Sentiment     *SpeechDetailSentiment `json:"sentiment,omitempty"`
	Session       *string                `json:"session,omitempty"`
	SourceUrl     *string                `json:"sourceUrl,omitempty"`
	Speaker       *Politician            `json:"speaker,omitempty"`
	SpeakerId     *string                `json:"speakerId,omitempty"`
	Title         *string                `json:"title,omitempty"`
	Topic         *Topic                 `json:"topic,omitempty"`
	TopicId       *string                `json:"topicId,omitempty"`
	Type          *string                `json:"type,omitempty"`
}

// SpeechDetailSentiment defines model for SpeechDetail.Sentiment.
type SpeechDetailSentiment string

// SpeechSnippet defines model for SpeechSnippet.
type SpeechSnippet struct {
	Date         *time.Time              `json:"date,omitempty"`
	FullSpeechId *string                 `json:"fullSpeechId,omitempty"`
	Id           *string                 `json:"id,omitempty"`
	Party        *string                 `json:"party,omitempty"`
	Sentiment    *SpeechSnippetSentiment `json:"sentiment,omitempty"`
	Speaker      *string                 `json:"speaker,omitempty"`
	Text         *string                 `json:"text,omitempty"`
	TopicId      *string                 `json:"topicId,omitempty"`
}

// SpeechSnippetSentiment defines model for SpeechSnippet.Sentiment.
type SpeechSnippetSentiment string

// TopTopic defines model for TopTopic.
type TopTopic struct {
	Stance *string `json:"stance,omitempty"`
	Topic  *string `json:"topic,omitempty"`
}

// Topic defines model for Topic.
type Topic struct {
	Category  *string     `json:"category,omitempty"`
	Id        *string     `json:"id,omitempty"`
	Relevance *int        `json:"relevance,omitempty"`
	Title     *string     `json:"title,omitempty"`
	Trend     *TopicTrend `json:"trend,omitempty"`
}

// TopicTrend defines model for Topic.Trend.
type TopicTrend string

// TopicDetail defines model for TopicDetail.
type TopicDetail struct {
	Category       *string           `json:"category,omitempty"`
	Id             *string           `json:"id,omitempty"`
	Legislation    *[]Legislation    `json:"legislation,omitempty"`
	PartyPositions *[]PartyPosition  `json:"partyPositions,omitempty"`
	PositionData   *[]TrendDataPoint `json:"positionData,omitempty"`
	Relevance      *int              `json:"relevance,omitempty"`
	Speeches       *[]SpeechSnippet  `json:"speeches,omitempty"`
	Stakeholders   *struct {
		Contra *[]Politician `json:"contra,omitempty"`
		Pro    *[]Politician `json:"pro,omitempty"`
	} `json:"stakeholders,omitempty"`
	Title     *string           `json:"title,omitempty"`
	Trend     *TopicDetailTrend `json:"trend,omitempty"`
	TrendData *[]TrendDataPoint `json:"trendData,omitempty"`
}

// TopicDetailTrend defines model for TopicDetail.Trend.
type TopicDetailTrend string

// TrendDataPoint defines model for TrendDataPoint.
type TrendDataPoint struct {
	Date  *string  `json:"date,omitempty"`
	Value *float32 `json:"value,omitempty"`
}

// GetPoliticiansParams defines parameters for GetPoliticians.
type GetPoliticiansParams struct {
	// Ids Comma-separated list of IDs to filter by.
	Ids *string `form:"ids,omitempty" json:"ids,omitempty"`
}

// GetSearchParams defines parameters for GetSearch.
type GetSearchParams struct {
	// Q The search query string.
	Q *string `form:"q,omitempty" json:"q,omitempty"`
}

// PostCampaignsJSONRequestBody defines body for PostCampaigns for application/json ContentType.
type PostCampaignsJSONRequestBody = CampaignInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all alerts
	// (GET /alerts)
	GetAlerts(w http.ResponseWriter, r *http.Request)
	// Get Bundestag session status
	// (GET /bundestag/status)
	GetBundestagStatus(w http.ResponseWriter, r *http.Request)
	// List all campaigns
	// (GET /campaigns)
	GetCampaigns(w http.ResponseWriter, r *http.Request)
	// Create a new campaign
	// (POST /campaigns)
	PostCampaigns(w http.ResponseWriter, r *http.Request)
	// Get a specific campaign
	// (GET /campaigns/{id})
	GetCampaignsId(w http.ResponseWriter, r *http.Request, id string)
	// Get dashboard data
	// (GET /dashboard)
	GetDashboard(w http.ResponseWriter, r *http.Request)
	// Health check endpoint
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// List all politicians
	// (GET /politicians)
	GetPoliticians(w http.ResponseWriter, r *http.Request, params GetPoliticiansParams)
	// Get a specific politician
	// (GET /politicians/{id})
	GetPoliticiansId(w http.ResponseWriter, r *http.Request, id string)
	// List all reports
	// (GET /reports)
	GetReports(w http.ResponseWriter, r *http.Request)
	// Global search
	// (GET /search)
	GetSearch(w http.ResponseWriter, r *http.Request, params GetSearchParams)
	// List all speeches
	// (GET /speeches)
	GetSpeeches(w http.ResponseWriter, r *http.Request)
	// Get a specific speech
	// (GET /speeches/{id})
	GetSpeechesId(w http.ResponseWriter, r *http.Request, id string)
	// List all topics
	// (GET /topics)
	GetTopics(w http.ResponseWriter, r *http.Request)
	// Get a specific topic
	// (GET /topics/{id})
	GetTopicsId(w http.ResponseWriter, r *http.Request, id string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAlerts operation middleware
func (siw *ServerInterfaceWrapper) GetAlerts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAlerts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBundestagStatus operation middleware
func (siw *ServerInterfaceWrapper) GetBundestagStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBundestagStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCampaigns operation middleware
func (siw *ServerInterfaceWrapper) GetCampaigns(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCampaigns(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostCampaigns operation middleware
func (siw *ServerInterfaceWrapper) PostCampaigns(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostCampaigns(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCampaignsId operation middleware
func (siw *ServerInterfaceWrapper) GetCampaignsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCampaignsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDashboard operation middleware
func (siw *ServerInterfaceWrapper) GetDashboard(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDashboard(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPoliticians operation middleware
func (siw *ServerInterfaceWrapper) GetPoliticians(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPoliticiansParams

	// ------------- Optional query parameter "ids" -------------

	err = runtime.BindQueryParameter("form", true, false, "ids", r.URL.Query(), &params.Ids)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ids", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPoliticians(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPoliticiansId operation middleware
func (siw *ServerInterfaceWrapper) GetPoliticiansId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPoliticiansId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReports operation middleware
func (siw *ServerInterfaceWrapper) GetReports(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReports(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSearch operation middleware
func (siw *ServerInterfaceWrapper) GetSearch(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSearchParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", r.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSearch(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSpeeches operation middleware
func (siw *ServerInterfaceWrapper) GetSpeeches(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSpeeches(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSpeechesId operation middleware
func (siw *ServerInterfaceWrapper) GetSpeechesId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSpeechesId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTopics operation middleware
func (siw *ServerInterfaceWrapper) GetTopics(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTopics(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTopicsId operation middleware
func (siw *ServerInterfaceWrapper) GetTopicsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTopicsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/alerts", wrapper.GetAlerts)
	m.HandleFunc("GET "+options.BaseURL+"/bundestag/status", wrapper.GetBundestagStatus)
	m.HandleFunc("GET "+options.BaseURL+"/campaigns", wrapper.GetCampaigns)
	m.HandleFunc("POST "+options.BaseURL+"/campaigns", wrapper.PostCampaigns)
	m.HandleFunc("GET "+options.BaseURL+"/campaigns/{id}", wrapper.GetCampaignsId)
	m.HandleFunc("GET "+options.BaseURL+"/dashboard", wrapper.GetDashboard)
	m.HandleFunc("GET "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc("GET "+options.BaseURL+"/politicians", wrapper.GetPoliticians)
	m.HandleFunc("GET "+options.BaseURL+"/politicians/{id}", wrapper.GetPoliticiansId)
	m.HandleFunc("GET "+options.BaseURL+"/reports", wrapper.GetReports)
	m.HandleFunc("GET "+options.BaseURL+"/search", wrapper.GetSearch)
	m.HandleFunc("GET "+options.BaseURL+"/speeches", wrapper.GetSpeeches)
	m.HandleFunc("GET "+options.BaseURL+"/speeches/{id}", wrapper.GetSpeechesId)
	m.HandleFunc("GET "+options.BaseURL+"/topics", wrapper.GetTopics)
	m.HandleFunc("GET "+options.BaseURL+"/topics/{id}", wrapper.GetTopicsId)

	return m
}
