//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AlertType.
const (
	AlertTypeAlert   AlertType = "alert"
	AlertTypeInfo    AlertType = "info"
	AlertTypeSuccess AlertType = "success"
)

// Defines values for FullSpeechSentiment.
const (
	FullSpeechSentimentNegativ      FullSpeechSentiment = "negativ"
	FullSpeechSentimentNeutral      FullSpeechSentiment = "neutral"
	FullSpeechSentimentPositiv      FullSpeechSentiment = "positiv"
	FullSpeechSentimentStarkNegativ FullSpeechSentiment = "stark negativ"
	FullSpeechSentimentStarkPositiv FullSpeechSentiment = "stark positiv"
)

// Defines values for PartyContributionFactor.
const (
	PartyContributionFactorHigh   PartyContributionFactor = "high"
	PartyContributionFactorLow    PartyContributionFactor = "low"
	PartyContributionFactorMedium PartyContributionFactor = "medium"
)

// Defines values for PartyDetailContributionFactor.
const (
	PartyDetailContributionFactorHigh   PartyDetailContributionFactor = "high"
	PartyDetailContributionFactorLow    PartyDetailContributionFactor = "low"
	PartyDetailContributionFactorMedium PartyDetailContributionFactor = "medium"
)

// Defines values for PoliticianContributionFactor.
const (
	PoliticianContributionFactorHigh   PoliticianContributionFactor = "high"
	PoliticianContributionFactorLow    PoliticianContributionFactor = "low"
	PoliticianContributionFactorMedium PoliticianContributionFactor = "medium"
)

// Defines values for PoliticianDetailContributionFactor.
const (
	PoliticianDetailContributionFactorHigh   PoliticianDetailContributionFactor = "high"
	PoliticianDetailContributionFactorLow    PoliticianDetailContributionFactor = "low"
	PoliticianDetailContributionFactorMedium PoliticianDetailContributionFactor = "medium"
)

// Defines values for SpeechDetailSentiment.
const (
	SpeechDetailSentimentNegativ      SpeechDetailSentiment = "negativ"
	SpeechDetailSentimentNeutral      SpeechDetailSentiment = "neutral"
	SpeechDetailSentimentPositiv      SpeechDetailSentiment = "positiv"
	SpeechDetailSentimentStarkNegativ SpeechDetailSentiment = "stark negativ"
	SpeechDetailSentimentStarkPositiv SpeechDetailSentiment = "stark positiv"
)

// Defines values for SpeechSnippetSentiment.
const (
	Negativ      SpeechSnippetSentiment = "negativ"
	Neutral      SpeechSnippetSentiment = "neutral"
	Positiv      SpeechSnippetSentiment = "positiv"
	StarkNegativ SpeechSnippetSentiment = "stark negativ"
	StarkPositiv SpeechSnippetSentiment = "stark positiv"
)

// Defines values for TimeRangeFilter.
const (
	Last2Years  TimeRangeFilter = "last_2_years"
	Last5Years  TimeRangeFilter = "last_5_years"
	Last6Months TimeRangeFilter = "last_6_months"
	LastMonth   TimeRangeFilter = "last_month"
	LastYear    TimeRangeFilter = "last_year"
	Max         TimeRangeFilter = "max"
	Ytd         TimeRangeFilter = "ytd"
)

// Defines values for TopicTrend.
const (
	TopicTrendDown   TopicTrend = "down"
	TopicTrendStable TopicTrend = "stable"
	TopicTrendUp     TopicTrend = "up"
)

// Defines values for TopicDetailTrend.
const (
	TopicDetailTrendDown   TopicDetailTrend = "down"
	TopicDetailTrendStable TopicDetailTrend = "stable"
	TopicDetailTrendUp     TopicDetailTrend = "up"
)

// ActivePolitician defines model for ActivePolitician.
type ActivePolitician struct {
	// Name Full name of the politician
	Name string `json:"name"`

	// NumSpeeches Number of speeches given by this politician
	NumSpeeches int `json:"numSpeeches"`

	// Party Political party or parliamentary group
	Party string `json:"party"`

	// WordCount Total number of words spoken by this politician
	WordCount int `json:"wordCount"`
}

// Alert defines model for Alert.
type Alert struct {
	Category  *string              `json:"category,omitempty"`
	Details   *NotificationDetails `json:"details,omitempty"`
	Id        *string              `json:"id,omitempty"`
	Message   *string              `json:"message,omitempty"`
	Timestamp *time.Time           `json:"timestamp,omitempty"`
	Title     *string              `json:"title,omitempty"`
	Type      *AlertType           `json:"type,omitempty"`
}

// AlertType defines model for Alert.Type.
type AlertType string

// AnalysisOverTimePoint defines model for AnalysisOverTimePoint.
type AnalysisOverTimePoint struct {
	// Period Start of the time bucket (e.g. week or month).
	Period *openapi_types.Date `json:"period,omitempty"`

	// Relevance Aggregated relevance for the period.
	Relevance *float32 `json:"relevance,omitempty"`

	// Sentiment Aggregated sentiment for the period.
	Sentiment *float32 `json:"sentiment,omitempty"`
}

// AnalysisOverTimeResponse defines model for AnalysisOverTimeResponse.
type AnalysisOverTimeResponse struct {
	// Series Time-ordered data points (relevance and sentiment per period).
	Series *[]AnalysisOverTimePoint `json:"series,omitempty"`
}

// DashboardData defines model for DashboardData.
type DashboardData struct {
	Alerts    *[]Alert          `json:"alerts,omitempty"`
	Stats     *[]DashboardStats `json:"stats,omitempty"`
	TrendData *[]TrendDataPoint `json:"trendData,omitempty"`
}

// DashboardStats defines model for DashboardStats.
type DashboardStats struct {
	Change     *string `json:"change,omitempty"`
	ChangeType *string `json:"changeType,omitempty"`
	Name       *string `json:"name,omitempty"`
	Value      *string `json:"value,omitempty"`
}

// ElectionPeriod defines model for ElectionPeriod.
type ElectionPeriod struct {
	// EndDate End date of the election period (null if ongoing).
	EndDate *openapi_types.Date `json:"end_date"`

	// Id Unique identifier for the election period.
	Id *int `json:"id,omitempty"`

	// Number The election period number (e.g., 20 for the 20th Bundestag).
	Number *int `json:"number,omitempty"`

	// StartDate Start date of the election period.
	StartDate *openapi_types.Date `json:"start_date,omitempty"`
}

// FullSpeech defines model for FullSpeech.
type FullSpeech struct {
	Content       *string              `json:"content,omitempty"`
	Date          *time.Time           `json:"date,omitempty"`
	Duration      *string              `json:"duration,omitempty"`
	Id            *string              `json:"id,omitempty"`
	RelatedTopics *[]string            `json:"relatedTopics,omitempty"`
	Sentiment     *FullSpeechSentiment `json:"sentiment,omitempty"`
	Session       *string              `json:"session,omitempty"`
	SourceUrl     *string              `json:"sourceUrl,omitempty"`
	SpeakerId     *string              `json:"speakerId,omitempty"`
	Title         *string              `json:"title,omitempty"`
	TopicId       *string              `json:"topicId,omitempty"`
	Type          *string              `json:"type,omitempty"`
}

// FullSpeechSentiment defines model for FullSpeech.Sentiment.
type FullSpeechSentiment string

// NotificationDetails defines model for NotificationDetails.
type NotificationDetails struct {
	After    *string `json:"after,omitempty"`
	Before   *string `json:"before,omitempty"`
	Reason   *string `json:"reason,omitempty"`
	Source   *string `json:"source,omitempty"`
	SpeechId *string `json:"speechId,omitempty"`
}

// PaginatedPoliticians Paginated response containing a page of politicians and pagination metadata.
type PaginatedPoliticians struct {
	// Data Page of politicians.
	Data []Politician `json:"data"`

	// Page Current page (1-based), computed by backend from offset and page_size.
	Page int `json:"page"`

	// PageSize Number of items per page.
	PageSize int `json:"page_size"`

	// TotalItems Total number of politicians across all pages.
	TotalItems int `json:"total_items"`
}

// PaginatedTopics Paginated response containing a page of topics and pagination metadata.
type PaginatedTopics struct {
	// Data Page of topics.
	Data []Topic `json:"data"`

	// Page Current page (1-based), computed by backend from offset and page_size.
	Page int `json:"page"`

	// PageSize Number of items per page (sent by frontend, echoed by backend).
	PageSize int `json:"page_size"`

	// TotalItems Total number of topics across all pages (sent by backend).
	TotalItems int `json:"total_items"`
}

// ParliamentaryGroup defines model for ParliamentaryGroup.
type ParliamentaryGroup struct {
	Id   *int    `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// Party defines model for Party.
type Party struct {
	// ContributionFactor Contribution factor level
	ContributionFactor *PartyContributionFactor `json:"contributionFactor,omitempty"`
	Id                 *string                  `json:"id,omitempty"`

	// Name Party name/abbreviation
	Name *string `json:"name,omitempty"`

	// NumSpeeches Number of speeches by party members in current year
	NumSpeeches *int `json:"numSpeeches,omitempty"`

	// NumTopics Number of top topics for this party
	NumTopics *int        `json:"numTopics,omitempty"`
	TopTopics *[]TopTopic `json:"topTopics,omitempty"`

	// Volatility Volatility level (Niedrig, Mittel, Hoch)
	Volatility *string `json:"volatility,omitempty"`
}

// PartyContributionFactor Contribution factor level
type PartyContributionFactor string

// PartyDetail defines model for PartyDetail.
type PartyDetail struct {
	// ActivityData Activity trend over time
	ActivityData *[]TrendDataPoint `json:"activityData,omitempty"`

	// ContributionFactor Contribution factor level
	ContributionFactor *PartyDetailContributionFactor `json:"contributionFactor,omitempty"`

	// Drucksachen Recent printed papers (Drucksachen)
	Drucksachen *[]PrintedPaper `json:"drucksachen,omitempty"`
	Id          *string         `json:"id,omitempty"`

	// Members Party members
	Members *[]Politician `json:"members,omitempty"`

	// Name Party name/abbreviation
	Name *string `json:"name,omitempty"`

	// NumSpeeches Number of speeches by party members in current year
	NumSpeeches *int `json:"numSpeeches,omitempty"`

	// NumTopics Number of top topics for this party
	NumTopics *int `json:"numTopics,omitempty"`

	// RecentSpeeches Recent speeches by party members
	RecentSpeeches *[]SpeechSnippet `json:"recentSpeeches,omitempty"`
	TopTopics      *[]TopTopic      `json:"topTopics,omitempty"`

	// Volatility Volatility level (Niedrig, Mittel, Hoch)
	Volatility *string `json:"volatility,omitempty"`
}

// PartyDetailContributionFactor Contribution factor level
type PartyDetailContributionFactor string

// PartyPosition defines model for PartyPosition.
type PartyPosition struct {
	// GroupId Parliamentary group ID
	GroupId   *int     `json:"groupId,omitempty"`
	Party     *string  `json:"party,omitempty"`
	Relevance *float32 `json:"relevance,omitempty"`
	Sentiment *float32 `json:"sentiment,omitempty"`
}

// Politician defines model for Politician.
type Politician struct {
	// ContributionFactor Contribution factor level
	ContributionFactor *PoliticianContributionFactor `json:"contributionFactor,omitempty"`
	Id                 *string                       `json:"id,omitempty"`
	Name               *string                       `json:"name,omitempty"`

	// NumSpeeches Number of speeches given by this politician
	NumSpeeches *int        `json:"numSpeeches,omitempty"`
	Party       *string     `json:"party,omitempty"`
	Role        *string     `json:"role,omitempty"`
	TopTopics   *[]TopTopic `json:"topTopics,omitempty"`
	Volatility  *string     `json:"volatility,omitempty"`
}

// PoliticianContributionFactor Contribution factor level
type PoliticianContributionFactor string

// PoliticianDetail defines model for PoliticianDetail.
type PoliticianDetail struct {
	// ContributionFactor Contribution factor level
	ContributionFactor *PoliticianDetailContributionFactor `json:"contributionFactor,omitempty"`
	Id                 *string                             `json:"id,omitempty"`
	Name               *string                             `json:"name,omitempty"`

	// NumSpeeches Number of speeches given by this politician
	NumSpeeches *int             `json:"numSpeeches,omitempty"`
	Party       *string          `json:"party,omitempty"`
	Role        *string          `json:"role,omitempty"`
	Speeches    *[]SpeechSnippet `json:"speeches,omitempty"`
	TopTopics   *[]TopTopic      `json:"topTopics,omitempty"`
	Volatility  *string          `json:"volatility,omitempty"`
}

// PoliticianDetailContributionFactor Contribution factor level
type PoliticianDetailContributionFactor string

// PrintedPaper defines model for PrintedPaper.
type PrintedPaper struct {
	Date *time.Time `json:"date,omitempty"`
	Id   *string    `json:"id,omitempty"`

	// Number Document number (e.g., 20/1234)
	Number *string `json:"number,omitempty"`
	Title  *string `json:"title,omitempty"`

	// Type Document type (e.g., Antrag, Gesetzentwurf)
	Type *string `json:"type,omitempty"`
}

// Report defines model for Report.
type Report struct {
	Date *time.Time `json:"date,omitempty"`
	Id   *int       `json:"id,omitempty"`
	Name *string    `json:"name,omitempty"`
	Size *string    `json:"size,omitempty"`
}

// SearchResults defines model for SearchResults.
type SearchResults struct {
	Politicians *[]Politician `json:"politicians,omitempty"`
	Topics      *[]Topic      `json:"topics,omitempty"`
}

// SessionStatus defines model for SessionStatus.
type SessionStatus struct {
	Datum          *time.Time `json:"datum,omitempty"`
	Error          *bool      `json:"error,omitempty"`
	Label          *string    `json:"label,omitempty"`
	Live           *bool      `json:"live,omitempty"`
	NextDatum      *time.Time `json:"nextDatum"`
	Sitzungsnummer *string    `json:"sitzungsnummer,omitempty"`
	Titel          *string    `json:"titel,omitempty"`
	Wahlperiode    *int       `json:"wahlperiode,omitempty"`
}

// SpeechDetail defines model for SpeechDetail.
type SpeechDetail struct {
	Content       *string                `json:"content,omitempty"`
	Date          *time.Time             `json:"date,omitempty"`
	Duration      *string                `json:"duration,omitempty"`
	Id            *string                `json:"id,omitempty"`
	RelatedTopics *[]string              `json:"relatedTopics,omitempty"`
	Sentiment     *SpeechDetailSentiment `json:"sentiment,omitempty"`
	Session       *string                `json:"session,omitempty"`
	SourceUrl     *string                `json:"sourceUrl,omitempty"`
	Speaker       *Politician            `json:"speaker,omitempty"`
	SpeakerId     *string                `json:"speakerId,omitempty"`
	Title         *string                `json:"title,omitempty"`
	Topic         *Topic                 `json:"topic,omitempty"`
	TopicId       *string                `json:"topicId,omitempty"`
	Type          *string                `json:"type,omitempty"`
}

// SpeechDetailSentiment defines model for SpeechDetail.Sentiment.
type SpeechDetailSentiment string

// SpeechSnippet defines model for SpeechSnippet.
type SpeechSnippet struct {
	Date         *time.Time              `json:"date,omitempty"`
	FullSpeechId *string                 `json:"fullSpeechId,omitempty"`
	Id           *string                 `json:"id,omitempty"`
	Party        *string                 `json:"party,omitempty"`
	Sentiment    *SpeechSnippetSentiment `json:"sentiment,omitempty"`
	Speaker      *string                 `json:"speaker,omitempty"`
	Text         *string                 `json:"text,omitempty"`
	TopicId      *string                 `json:"topicId,omitempty"`
}

// SpeechSnippetSentiment defines model for SpeechSnippet.Sentiment.
type SpeechSnippetSentiment string

// TimeRangeFilter Time window for time-series data. Supported values:
// - last_month - last 30 days
// - last_6_months - last 6 months
// - ytd - year to date
// - last_year - last 12 months
// - last_2_years - last 2 years
// - last_5_years - last 5 years
// - max - all available data
type TimeRangeFilter string

// TopTopic defines model for TopTopic.
type TopTopic struct {
	// Sentiment Sentiment score for this topic (-1 to 1)
	Sentiment *float32 `json:"sentiment,omitempty"`

	// SpeechCount Number of speeches given on this topic
	SpeechCount *int    `json:"speechCount,omitempty"`
	Stance      *string `json:"stance,omitempty"`
	Topic       *string `json:"topic,omitempty"`
}

// Topic defines model for Topic.
type Topic struct {
	Category *string `json:"category,omitempty"`
	Id       *string `json:"id,omitempty"`

	// Relevance Relevance score for the topic.
	Relevance *float32 `json:"relevance,omitempty"`

	// Sentiment Aggregated sentiment score for the topic, -1 to 1 (display as -100 to +100). Negative = negative sentiment, positive = positive sentiment, 0 = neutral.
	Sentiment *float32    `json:"sentiment,omitempty"`
	Title     *string     `json:"title,omitempty"`
	Trend     *TopicTrend `json:"trend,omitempty"`
}

// TopicTrend defines model for Topic.Trend.
type TopicTrend string

// TopicDetail defines model for TopicDetail.
type TopicDetail struct {
	Category       *string           `json:"category,omitempty"`
	Id             *string           `json:"id,omitempty"`
	PartyPositions *[]PartyPosition  `json:"partyPositions,omitempty"`
	PositionData   *[]TrendDataPoint `json:"positionData,omitempty"`

	// Relevance Relevance score for the topic.
	Relevance *float32 `json:"relevance,omitempty"`

	// Sentiment Aggregated sentiment score for the topic, -1 to 1 (display as -100 to +100). Negative = negative sentiment, positive = positive sentiment, 0 = neutral.
	Sentiment    *float32         `json:"sentiment,omitempty"`
	Speeches     *[]SpeechSnippet `json:"speeches,omitempty"`
	Stakeholders *struct {
		Contra *[]Politician `json:"contra,omitempty"`
		Pro    *[]Politician `json:"pro,omitempty"`
	} `json:"stakeholders,omitempty"`
	Title     *string           `json:"title,omitempty"`
	Trend     *TopicDetailTrend `json:"trend,omitempty"`
	TrendData *[]TrendDataPoint `json:"trendData,omitempty"`
}

// TopicDetailTrend defines model for TopicDetail.Trend.
type TopicDetailTrend string

// TrendDataPoint defines model for TrendDataPoint.
type TrendDataPoint struct {
	Date  *string  `json:"date,omitempty"`
	Value *float32 `json:"value,omitempty"`
}

// WordCloudItem defines model for WordCloudItem.
type WordCloudItem struct {
	// Weight The weight/frequency of the word.
	Weight float32 `json:"weight"`

	// Word The word from the politician's speeches.
	Word string `json:"word"`
}

// ElectionPeriodFilter defines model for ElectionPeriodFilter.
type ElectionPeriodFilter = int

// Offset defines model for Offset.
type Offset = int

// PageSize defines model for PageSize.
type PageSize = int

// GetAnalysisTimeSeriesParams defines parameters for GetAnalysisTimeSeries.
type GetAnalysisTimeSeriesParams struct {
	// TimeRange Time window for the time series.
	TimeRange TimeRangeFilter `form:"time_range" json:"time_range"`

	// TopicId Filter by topic ID.
	TopicId *int `form:"topic_id,omitempty" json:"topic_id,omitempty"`

	// PersonId Filter by person (politician) ID.
	PersonId *int `form:"person_id,omitempty" json:"person_id,omitempty"`

	// GroupId Filter by parliamentary group ID.
	GroupId *int `form:"group_id,omitempty" json:"group_id,omitempty"`
}

// GetParliamentaryGroupsParams defines parameters for GetParliamentaryGroups.
type GetParliamentaryGroupsParams struct {
	// ElectionPeriod Election period ID.
	ElectionPeriod int `form:"election_period" json:"election_period"`
}

// GetPartiesParams defines parameters for GetParties.
type GetPartiesParams struct {
	// ElectionPeriod Filter by election period (Wahlperiode).
	ElectionPeriod ElectionPeriodFilter `form:"election_period" json:"election_period"`
}

// GetPartiesIdParams defines parameters for GetPartiesId.
type GetPartiesIdParams struct {
	// ElectionPeriod Filter by election period (Wahlperiode).
	ElectionPeriod ElectionPeriodFilter `form:"election_period" json:"election_period"`

	// TimeRange Time window for the time series.
	TimeRange TimeRangeFilter `form:"time_range" json:"time_range"`
}

// GetPoliticiansParams defines parameters for GetPoliticians.
type GetPoliticiansParams struct {
	// PageSize Number of items per page. If not provided, all items are returned. Maximum is 100.
	PageSize *PageSize `form:"page_size,omitempty" json:"page_size,omitempty"`

	// Offset Number of items to skip (for pagination). Default is 0.
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// ElectionPeriod Filter politicians by election period ID.
	ElectionPeriod int `form:"election_period" json:"election_period"`

	// GroupId Filter politicians by parliamentary group ID.
	GroupId *int `form:"group_id,omitempty" json:"group_id,omitempty"`
}

// GetPoliticiansLeastActiveParams defines parameters for GetPoliticiansLeastActive.
type GetPoliticiansLeastActiveParams struct {
	// Limit Maximum number of politicians to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// ElectionPeriod Filter by election period ID. Defaults to the latest election period.
	ElectionPeriod *int `form:"election_period,omitempty" json:"election_period,omitempty"`
}

// GetPoliticiansMostActiveParams defines parameters for GetPoliticiansMostActive.
type GetPoliticiansMostActiveParams struct {
	// Limit Maximum number of politicians to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// ElectionPeriod Filter by election period ID. Defaults to the latest election period.
	ElectionPeriod *int `form:"election_period,omitempty" json:"election_period,omitempty"`
}

// GetPoliticiansIdParams defines parameters for GetPoliticiansId.
type GetPoliticiansIdParams struct {
	// ElectionPeriod Filter by election period (Wahlperiode).
	ElectionPeriod ElectionPeriodFilter `form:"election_period" json:"election_period"`

	// TimeRange Time window for the time series.
	TimeRange TimeRangeFilter `form:"time_range" json:"time_range"`
}

// GetPoliticiansIdActivityParams defines parameters for GetPoliticiansIdActivity.
type GetPoliticiansIdActivityParams struct {
	// TimeRange Time window for the time series.
	TimeRange TimeRangeFilter `form:"time_range" json:"time_range"`
}

// GetPoliticiansIdSimilarParams defines parameters for GetPoliticiansIdSimilar.
type GetPoliticiansIdSimilarParams struct {
	// ElectionPeriod Filter by election period (Wahlperiode).
	ElectionPeriod ElectionPeriodFilter `form:"election_period" json:"election_period"`
}

// GetSearchParams defines parameters for GetSearch.
type GetSearchParams struct {
	// Q The search query string.
	Q *string `form:"q,omitempty" json:"q,omitempty"`
}

// GetTopicsParams defines parameters for GetTopics.
type GetTopicsParams struct {
	// PageSize Number of items per page. If not provided, all items are returned. Maximum is 100.
	PageSize *PageSize `form:"page_size,omitempty" json:"page_size,omitempty"`

	// Offset Number of items to skip (for pagination). Default is 0.
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all alerts
	// (GET /alerts)
	GetAlerts(w http.ResponseWriter, r *http.Request)
	// Time series
	// (GET /analysis/time-series)
	GetAnalysisTimeSeries(w http.ResponseWriter, r *http.Request, params GetAnalysisTimeSeriesParams)
	// Get Bundestag session status
	// (GET /bundestag/status)
	GetBundestagStatus(w http.ResponseWriter, r *http.Request)
	// Get dashboard data
	// (GET /dashboard)
	GetDashboard(w http.ResponseWriter, r *http.Request)
	// List all election periods
	// (GET /election-periods)
	GetElectionPeriods(w http.ResponseWriter, r *http.Request)
	// Health check endpoint
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// List parliamentary groups for election period
	// (GET /parliamentary-groups)
	GetParliamentaryGroups(w http.ResponseWriter, r *http.Request, params GetParliamentaryGroupsParams)
	// List all parties
	// (GET /parties)
	GetParties(w http.ResponseWriter, r *http.Request, params GetPartiesParams)
	// Get a specific party
	// (GET /parties/{id})
	GetPartiesId(w http.ResponseWriter, r *http.Request, id string, params GetPartiesIdParams)
	// List all politicians
	// (GET /politicians)
	GetPoliticians(w http.ResponseWriter, r *http.Request, params GetPoliticiansParams)
	// Get least active politicians
	// (GET /politicians/least-active)
	GetPoliticiansLeastActive(w http.ResponseWriter, r *http.Request, params GetPoliticiansLeastActiveParams)
	// Get most active politicians
	// (GET /politicians/most-active)
	GetPoliticiansMostActive(w http.ResponseWriter, r *http.Request, params GetPoliticiansMostActiveParams)
	// Get a specific politician
	// (GET /politicians/{id})
	GetPoliticiansId(w http.ResponseWriter, r *http.Request, id string, params GetPoliticiansIdParams)
	// Get politician activity time series
	// (GET /politicians/{id}/activity)
	GetPoliticiansIdActivity(w http.ResponseWriter, r *http.Request, id string, params GetPoliticiansIdActivityParams)
	// Get similar politicians
	// (GET /politicians/{id}/similar)
	GetPoliticiansIdSimilar(w http.ResponseWriter, r *http.Request, id string, params GetPoliticiansIdSimilarParams)
	// Get politician wordcloud
	// (GET /politicians/{id}/wordcloud)
	GetPoliticiansIdWordcloud(w http.ResponseWriter, r *http.Request, id string)
	// List all reports
	// (GET /reports)
	GetReports(w http.ResponseWriter, r *http.Request)
	// Global search
	// (GET /search)
	GetSearch(w http.ResponseWriter, r *http.Request, params GetSearchParams)
	// List all speeches
	// (GET /speeches)
	GetSpeeches(w http.ResponseWriter, r *http.Request)
	// Get a specific speech
	// (GET /speeches/{id})
	GetSpeechesId(w http.ResponseWriter, r *http.Request, id string)
	// List all topics
	// (GET /topics)
	GetTopics(w http.ResponseWriter, r *http.Request, params GetTopicsParams)
	// Get a specific topic
	// (GET /topics/{id})
	GetTopicsId(w http.ResponseWriter, r *http.Request, id string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAlerts operation middleware
func (siw *ServerInterfaceWrapper) GetAlerts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAlerts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAnalysisTimeSeries operation middleware
func (siw *ServerInterfaceWrapper) GetAnalysisTimeSeries(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAnalysisTimeSeriesParams

	// ------------- Required query parameter "time_range" -------------

	if paramValue := r.URL.Query().Get("time_range"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "time_range"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "time_range", r.URL.Query(), &params.TimeRange)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "time_range", Err: err})
		return
	}

	// ------------- Optional query parameter "topic_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "topic_id", r.URL.Query(), &params.TopicId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "topic_id", Err: err})
		return
	}

	// ------------- Optional query parameter "person_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "person_id", r.URL.Query(), &params.PersonId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "person_id", Err: err})
		return
	}

	// ------------- Optional query parameter "group_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "group_id", r.URL.Query(), &params.GroupId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "group_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAnalysisTimeSeries(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBundestagStatus operation middleware
func (siw *ServerInterfaceWrapper) GetBundestagStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBundestagStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDashboard operation middleware
func (siw *ServerInterfaceWrapper) GetDashboard(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDashboard(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetElectionPeriods operation middleware
func (siw *ServerInterfaceWrapper) GetElectionPeriods(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetElectionPeriods(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetParliamentaryGroups operation middleware
func (siw *ServerInterfaceWrapper) GetParliamentaryGroups(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetParliamentaryGroupsParams

	// ------------- Required query parameter "election_period" -------------

	if paramValue := r.URL.Query().Get("election_period"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "election_period"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "election_period", r.URL.Query(), &params.ElectionPeriod)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "election_period", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetParliamentaryGroups(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetParties operation middleware
func (siw *ServerInterfaceWrapper) GetParties(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPartiesParams

	// ------------- Required query parameter "election_period" -------------

	if paramValue := r.URL.Query().Get("election_period"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "election_period"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "election_period", r.URL.Query(), &params.ElectionPeriod)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "election_period", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetParties(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPartiesId operation middleware
func (siw *ServerInterfaceWrapper) GetPartiesId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPartiesIdParams

	// ------------- Required query parameter "election_period" -------------

	if paramValue := r.URL.Query().Get("election_period"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "election_period"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "election_period", r.URL.Query(), &params.ElectionPeriod)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "election_period", Err: err})
		return
	}

	// ------------- Required query parameter "time_range" -------------

	if paramValue := r.URL.Query().Get("time_range"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "time_range"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "time_range", r.URL.Query(), &params.TimeRange)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "time_range", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPartiesId(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPoliticians operation middleware
func (siw *ServerInterfaceWrapper) GetPoliticians(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPoliticiansParams

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Required query parameter "election_period" -------------

	if paramValue := r.URL.Query().Get("election_period"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "election_period"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "election_period", r.URL.Query(), &params.ElectionPeriod)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "election_period", Err: err})
		return
	}

	// ------------- Optional query parameter "group_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "group_id", r.URL.Query(), &params.GroupId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "group_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPoliticians(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPoliticiansLeastActive operation middleware
func (siw *ServerInterfaceWrapper) GetPoliticiansLeastActive(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPoliticiansLeastActiveParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "election_period" -------------

	err = runtime.BindQueryParameter("form", true, false, "election_period", r.URL.Query(), &params.ElectionPeriod)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "election_period", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPoliticiansLeastActive(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPoliticiansMostActive operation middleware
func (siw *ServerInterfaceWrapper) GetPoliticiansMostActive(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPoliticiansMostActiveParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "election_period" -------------

	err = runtime.BindQueryParameter("form", true, false, "election_period", r.URL.Query(), &params.ElectionPeriod)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "election_period", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPoliticiansMostActive(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPoliticiansId operation middleware
func (siw *ServerInterfaceWrapper) GetPoliticiansId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPoliticiansIdParams

	// ------------- Required query parameter "election_period" -------------

	if paramValue := r.URL.Query().Get("election_period"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "election_period"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "election_period", r.URL.Query(), &params.ElectionPeriod)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "election_period", Err: err})
		return
	}

	// ------------- Required query parameter "time_range" -------------

	if paramValue := r.URL.Query().Get("time_range"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "time_range"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "time_range", r.URL.Query(), &params.TimeRange)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "time_range", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPoliticiansId(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPoliticiansIdActivity operation middleware
func (siw *ServerInterfaceWrapper) GetPoliticiansIdActivity(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPoliticiansIdActivityParams

	// ------------- Required query parameter "time_range" -------------

	if paramValue := r.URL.Query().Get("time_range"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "time_range"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "time_range", r.URL.Query(), &params.TimeRange)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "time_range", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPoliticiansIdActivity(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPoliticiansIdSimilar operation middleware
func (siw *ServerInterfaceWrapper) GetPoliticiansIdSimilar(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPoliticiansIdSimilarParams

	// ------------- Required query parameter "election_period" -------------

	if paramValue := r.URL.Query().Get("election_period"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "election_period"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "election_period", r.URL.Query(), &params.ElectionPeriod)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "election_period", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPoliticiansIdSimilar(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPoliticiansIdWordcloud operation middleware
func (siw *ServerInterfaceWrapper) GetPoliticiansIdWordcloud(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPoliticiansIdWordcloud(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReports operation middleware
func (siw *ServerInterfaceWrapper) GetReports(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReports(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSearch operation middleware
func (siw *ServerInterfaceWrapper) GetSearch(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSearchParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", r.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSearch(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSpeeches operation middleware
func (siw *ServerInterfaceWrapper) GetSpeeches(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSpeeches(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSpeechesId operation middleware
func (siw *ServerInterfaceWrapper) GetSpeechesId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSpeechesId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTopics operation middleware
func (siw *ServerInterfaceWrapper) GetTopics(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTopicsParams

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTopics(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTopicsId operation middleware
func (siw *ServerInterfaceWrapper) GetTopicsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTopicsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/alerts", wrapper.GetAlerts)
	m.HandleFunc("GET "+options.BaseURL+"/analysis/time-series", wrapper.GetAnalysisTimeSeries)
	m.HandleFunc("GET "+options.BaseURL+"/bundestag/status", wrapper.GetBundestagStatus)
	m.HandleFunc("GET "+options.BaseURL+"/dashboard", wrapper.GetDashboard)
	m.HandleFunc("GET "+options.BaseURL+"/election-periods", wrapper.GetElectionPeriods)
	m.HandleFunc("GET "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc("GET "+options.BaseURL+"/parliamentary-groups", wrapper.GetParliamentaryGroups)
	m.HandleFunc("GET "+options.BaseURL+"/parties", wrapper.GetParties)
	m.HandleFunc("GET "+options.BaseURL+"/parties/{id}", wrapper.GetPartiesId)
	m.HandleFunc("GET "+options.BaseURL+"/politicians", wrapper.GetPoliticians)
	m.HandleFunc("GET "+options.BaseURL+"/politicians/least-active", wrapper.GetPoliticiansLeastActive)
	m.HandleFunc("GET "+options.BaseURL+"/politicians/most-active", wrapper.GetPoliticiansMostActive)
	m.HandleFunc("GET "+options.BaseURL+"/politicians/{id}", wrapper.GetPoliticiansId)
	m.HandleFunc("GET "+options.BaseURL+"/politicians/{id}/activity", wrapper.GetPoliticiansIdActivity)
	m.HandleFunc("GET "+options.BaseURL+"/politicians/{id}/similar", wrapper.GetPoliticiansIdSimilar)
	m.HandleFunc("GET "+options.BaseURL+"/politicians/{id}/wordcloud", wrapper.GetPoliticiansIdWordcloud)
	m.HandleFunc("GET "+options.BaseURL+"/reports", wrapper.GetReports)
	m.HandleFunc("GET "+options.BaseURL+"/search", wrapper.GetSearch)
	m.HandleFunc("GET "+options.BaseURL+"/speeches", wrapper.GetSpeeches)
	m.HandleFunc("GET "+options.BaseURL+"/speeches/{id}", wrapper.GetSpeechesId)
	m.HandleFunc("GET "+options.BaseURL+"/topics", wrapper.GetTopics)
	m.HandleFunc("GET "+options.BaseURL+"/topics/{id}", wrapper.GetTopicsId)

	return m
}
